In [ ]:
# dataset: structured dataset Amazon–Google_1 (https://github.com/anhaidgroup/sparkly)

# Some simple experiments with the Amazon–Google_1 dataset

import pandas as pd

dataset_path ="../amazon_google"

df_amazon = pd.read_parquet("../amazon_google/table_a.parquet")
df_google = pd.read_parquet("../amazon_google/table_b.parquet")
df_gold = pd.read_parquet("../amazon_google/gold.parquet")

# use only the attributes to compare tuples
df_amazon_only_3_att = df_amazon[['title', 'manufacturer', 'price']] 
df_google_only_3_att = df_google[['title', 'manufacturer', 'price']]

In [15]:
df_amazon.columns

Index(['_id', 'title', 'description', 'manufacturer', 'price'], dtype='object')

In [ ]:
# full column width display for the Amazon dataset

with pd.option_context('display.max_colwidth', None):
    display(df_amazon_only_3_att.head())
    display(df_google_only_3_att.head())
    display(df_gold.head())
    display(df_amazon[df_amazon["_id"]==0])
    display(df_google[df_google["_id"]==1878])

,title,manufacturer,price
0,clickart 950 000 premier image pack ( dvd-rom ),broderbund,NaN
1,ca international arcserve lap/desktop oem 30pk,computer associates,NaN
2,noah 's ark activity center ( jewel case ages 3-8 ),victory multimedia,NaN
3,peachtree by sage premium accounting for nonprofits 2007,sage software,599.99
4,singing coach unlimited,carry-a-tune technologies,99.99

,title,manufacturer,price
0,learning quickbooks 2007,intuit,38.99
1,superstart ! fun with reading & writing !,<NA>,8.49
2,qb pos 6.0 basic software,intuit,637.99
3,math missions : the amazing arcade adventure ( grades 3-5 ),<NA>,12.95
4,production prem cs3 mac upgrad,adobe software,805.99

   id1   id2
0    0  1878
1    2  1881
2    3  1879
3    4  1905
4    6  1923

KeyError: 'id'